### ISSUE TITLE
Notice - PokeAPI is looking for help maintaining

### ISSUE THREAD

**Issue by tdmalone** [PokeAPI/pykemon#17]
Please see https://github.com/PokeAPI/pokeapi/issues/350#issuecomment-419698139 if you are interested in maintaining this repository. Thanks!

**Comment by tdmalone** [comment]
Apologies for the delay in getting back to you @kronopt!

I’m on mobile at the moment but have set myself a reminder for when I’m back at my computer - I will add you as a maintainer and add you to the PokeAPI organisation (if someone else doesn’t get to it before me :))

**Comment by Kronopt** [comment]
I will.
I'll just finish the cache implementation I've been working on and will submit it once it's done.
