### ISSUE TITLE
Resistances missing

### ISSUE THREAD

**Issue by ConorNevin** [PokeAPI/pykemon#2]
Trying to use the API to write a tool, and I noticed that the resistances for types seem to be missing from the Type API calls

**Comment by Kronopt** [comment]
Not relevant to this repo.
Pykemon is a wrapper for Pokeapi.co, issues related to it should be opened on [pokeapi](https://github.com/PokeAPI/pokeapi)

This can be closed

**Comment by Kronopt** [comment]
This should work as of the implementation of pokeapi v2.
This can be closed
