### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by robmuh** [PokeAPI/pykemon#5]
Just wondering before I fork and make a Python 3 compatible version to use in our school. (We don't/won't teach old Python.)

**Comment by Shad0wShayd3** [comment]
There actually is a Python 3 compatible version already available here: <https://github.com/CptnBrittish/pykemon>

**Comment by kasarov55555** [comment]
https://github.com/CptnBrittish/pykemon
Does NOT support Python 3(It tries to import modules that have been merged in Python 3, this can be fixed by using find and replace to rename to new merged module).

**Comment by Redjumpman** [comment]
@Anthony4444 can you explain what you mean by using find and replace to rename to new merged module? Do you mean merging all the pykemon modules and using find and replace to fix the calling of  all the classes?

**Comment by phalt** [comment]
@robmuh happy to accept a Pull Request that makes this support Py2 and Py3, instead of doing a fork!

**Comment by robmuh** [comment]
Perhaps eventually. Love what you guys are doing but for our purposes we decided to go with a local [FADB database](http://github.com/fadb/pokemon) for our kids programming and introducing data science concepts. Yours is still the best API to introduce the idea of APIs when one is needed.

**Comment by Kronopt** [comment]
This can be closed
