### ISSUE TITLE
Certain calls do not work.

### ISSUE THREAD

**Issue by ghost** [PokeAPI/pykemon#7]
I am using CptnBrittish/pykemon forked.

import pykemon
p = pykemon.get(pokemon='charizard')
print ('exp: ' + str(p.national_id))  
# AttributeError: 'Pokemon' object has no attribute 'national_id'

print ('exp: ' + str(p.male_femal_ratio)) 
# AttributeError: 'Pokemon' object has no attribute 'male_femal_ratio'

So national_id and male_femal_ratio do not work.
I need national_id for my program to work properly.

Species, ev_yield, and growth return nothing. These do not kill my project.

All other p.examples seem to work properly.

**Comment by Kronopt** [comment]
Works correctly as of pokeapi v2 implementation.
This can be closed
